export const driveResults = {
  "summary": {
    "generatedAt": "2026-06-18",
    "mainReport": "relatorio_geral_blinktracking_v2_drive.html",
    "scientificReport": "relatorio_cientifico_drive.html",
    "rescueReport": "zero_blink_rescue_report.html",
    "videosManifest": 71,
    "videosWithMetrics": 71,
    "failures": 0,
    "totalBlinks": 1273,
    "rawEyeBlinks": 2397,
    "bilateralBlinks": 1124,
    "unilateralLeftBlinks": 103,
    "unilateralRightBlinks": 46,
    "bilateralSymmetricBlinks": 988,
    "leftDominantBlinks": 121,
    "rightDominantBlinks": 15,
    "zeroCount": 20,
    "nonZeroCount": 51,
    "highReviewCount": 2,
    "durationHours": 3.15,
    "processingHours": 28.86,
    "medianRate": 2.24,
    "meanRate": 6.16,
    "medianBlinks": 4.0,
    "maxRate": 44.6,
    "maxBlinks": 141
  },
  "rescueSummary": {
    "videosReprocessed": 20,
    "successfulReprocess": 20,
    "confirmedByMainDetector": 0,
    "videosWithRescueCandidates": 18,
    "videosWithoutCandidates": 2,
    "totalCandidates": 87,
    "bilateralCandidates": 39,
    "unilateralCandidates": 48,
    "leftDominantCandidates": 25,
    "rightDominantCandidates": 35
  },
  "highReviewRows": [
    {
      "idx": 32,
      "grupo": "Paciente",
      "paciente": "Paciente 23 - Thamires Sousa da Silva",
      "video": "IMG_4498.MOV",
      "durationSeconds": 189.67,
      "fps": 239.48,
      "detectionRatio": 100.0,
      "totalBlinks": 141,
      "rawEyeBlinks": 282,
      "bilateralBlinks": 141,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 44.6,
      "meanDurationMs": 248.79,
      "meanCompleteness": 43.78,
      "completeBlinks": 0,
      "incompleteBlinks": 141,
      "elapsedSeconds": 939.72,
      "downloadSizeMb": 1308.4
    },
    {
      "idx": 52,
      "grupo": "Paciente",
      "paciente": "Paciente 36 - Silvania Guimarães ",
      "video": "IMG_6682.MOV",
      "durationSeconds": 188.92,
      "fps": 200.59,
      "detectionRatio": 100.0,
      "totalBlinks": 139,
      "rawEyeBlinks": 275,
      "bilateralBlinks": 136,
      "unilateralLeftBlinks": 1,
      "unilateralRightBlinks": 2,
      "blinkRatePerMinute": 44.15,
      "meanDurationMs": 165.98,
      "meanCompleteness": 36.32,
      "completeBlinks": 0,
      "incompleteBlinks": 139,
      "elapsedSeconds": 707.38,
      "downloadSizeMb": 1135.3
    }
  ],
  "zeroRows": [
    {
      "idx": 10,
      "grupo": "Paciente",
      "paciente": "Paciente 1 - Narciso Vieira",
      "video": "Cópia de IMG_2644.MOV",
      "durationSeconds": 182.3,
      "fps": 239.47,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 689.07,
      "downloadSizeMb": 1257.61
    },
    {
      "idx": 13,
      "grupo": "Paciente",
      "paciente": "Paciente 11 - Ivanilda dos Santos",
      "video": "Cópia de IMG_3763.MOV",
      "durationSeconds": 188.12,
      "fps": 154.03,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 595.1,
      "downloadSizeMb": 1235.35
    },
    {
      "idx": 15,
      "grupo": "Paciente",
      "paciente": "Paciente 13 - Pedro Gustavo Mendes Ponciano",
      "video": "Cópia de IMG_3940.MOV",
      "durationSeconds": 15.08,
      "fps": 153.56,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 84.2,
      "downloadSizeMb": 101.76
    },
    {
      "idx": 17,
      "grupo": "Paciente",
      "paciente": "Paciente 14 - Jocelia Santos de Oliveira",
      "video": "Cópia de IMG_3959.MOV",
      "durationSeconds": 187.06,
      "fps": 154.39,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 619.04,
      "downloadSizeMb": 1286.51
    },
    {
      "idx": 18,
      "grupo": "Paciente",
      "paciente": "Paciente 15 - Aline de Sousa Lima Otoni",
      "video": "Cópia de IMG_3976.MOV",
      "durationSeconds": 7.09,
      "fps": 152.55,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 28.07,
      "downloadSizeMb": 43.87
    },
    {
      "idx": 20,
      "grupo": "Paciente",
      "paciente": "Paciente 16 - Rosemary Jerk ",
      "video": "Cópia de IMG_4220.MOV",
      "durationSeconds": 10.51,
      "fps": 144.76,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 41.8,
      "downloadSizeMb": 68.86
    },
    {
      "idx": 22,
      "grupo": "Paciente",
      "paciente": "Paciente 17 - Thaissa Beatriz Costa Martins",
      "video": "Cópia de IMG_4246.MOV",
      "durationSeconds": 10.19,
      "fps": 144.32,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 36.89,
      "downloadSizeMb": 70.61
    },
    {
      "idx": 23,
      "grupo": "Paciente",
      "paciente": "Paciente 17 - Thaissa Beatriz Costa Martins",
      "video": "Cópia de IMG_4247.MOV",
      "durationSeconds": 187.32,
      "fps": 145.2,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 3963.11,
      "downloadSizeMb": 1167.13
    },
    {
      "idx": 29,
      "grupo": "Paciente",
      "paciente": "Paciente 21 - Robson Ferreira de Sousa",
      "video": "IMG_4449.MOV",
      "durationSeconds": 189.04,
      "fps": 239.48,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 895.35,
      "downloadSizeMb": 1578.83
    },
    {
      "idx": 34,
      "grupo": "Paciente",
      "paciente": "Paciente 25 - Alejandro da Silva Santos",
      "video": "IMG_4540.MOV",
      "durationSeconds": 70.02,
      "fps": 239.4,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 260.29,
      "downloadSizeMb": 474.78
    },
    {
      "idx": 35,
      "grupo": "Paciente",
      "paciente": "Paciente 25 - Alejandro da Silva Santos",
      "video": "IMG_4541.MOV",
      "durationSeconds": 183.86,
      "fps": 239.48,
      "detectionRatio": 99.82,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 3135.82,
      "downloadSizeMb": 1300.34
    },
    {
      "idx": 39,
      "grupo": "Paciente",
      "paciente": "Paciente 29 - Evandro Silva Siqueira",
      "video": "IMG_5030.MOV",
      "durationSeconds": 191.7,
      "fps": 153.42,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 701.87,
      "downloadSizeMb": 1151.24
    },
    {
      "idx": 40,
      "grupo": "Paciente",
      "paciente": "Paciente 3 - José Ivo da Silva",
      "video": "Cópia de IMG_2680.MOV",
      "durationSeconds": 10.04,
      "fps": 239.48,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 46.51,
      "downloadSizeMb": 76.24
    },
    {
      "idx": 47,
      "grupo": "Paciente",
      "paciente": "Paciente 33 - Maria Nilza Barbosa ",
      "video": "IMG_6375.MOV",
      "durationSeconds": 192.44,
      "fps": 29.99,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 157.06,
      "downloadSizeMb": 201.86
    },
    {
      "idx": 50,
      "grupo": "Paciente",
      "paciente": "Paciente 35 - Ricardo Mendonça Feitosa",
      "video": "IMG_6423.MOV",
      "durationSeconds": 38.79,
      "fps": 239.48,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 166.87,
      "downloadSizeMb": 233.83
    },
    {
      "idx": 51,
      "grupo": "Paciente",
      "paciente": "Paciente 35 - Ricardo Mendonça Feitosa",
      "video": "IMG_6424.MOV",
      "durationSeconds": 191.6,
      "fps": 239.48,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 818.55,
      "downloadSizeMb": 1321.7
    },
    {
      "idx": 59,
      "grupo": "Paciente",
      "paciente": "Paciente 42 - Márcia Verônica de Laurentis ",
      "video": "IMG_7575.MOV",
      "durationSeconds": 132.46,
      "fps": 169.06,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 1776.59,
      "downloadSizeMb": 795.96
    },
    {
      "idx": 60,
      "grupo": "Paciente",
      "paciente": "Paciente 42 - Márcia Verônica de Laurentis ",
      "video": "IMG_7576.MOV",
      "durationSeconds": 183.11,
      "fps": 169.06,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 1194.17,
      "downloadSizeMb": 1099.72
    },
    {
      "idx": 66,
      "grupo": "Paciente",
      "paciente": "Paciente 6 - Francisco Justiniano",
      "video": "Cópia de IMG_3103.MOV",
      "durationSeconds": 191.51,
      "fps": 235.81,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 2932.79,
      "downloadSizeMb": 1446.74
    },
    {
      "idx": 70,
      "grupo": "Paciente",
      "paciente": "Paciente 9 - Mariana Lambert",
      "video": "IMG_3653.MOV",
      "durationSeconds": 8.83,
      "fps": 152.25,
      "detectionRatio": 100.0,
      "totalBlinks": 0,
      "rawEyeBlinks": 0,
      "bilateralBlinks": 0,
      "unilateralLeftBlinks": 0,
      "unilateralRightBlinks": 0,
      "blinkRatePerMinute": 0.0,
      "meanDurationMs": 0.0,
      "meanCompleteness": 0.0,
      "completeBlinks": 0,
      "incompleteBlinks": 0,
      "elapsedSeconds": 69.33,
      "downloadSizeMb": 53.33
    }
  ],
  "rescueRows": [
    {
      "idx": 10,
      "paciente": "Paciente 1 - Narciso Vieira",
      "video": "Cópia de IMG_2644.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 13,
      "paciente": "Paciente 11 - Ivanilda dos Santos",
      "video": "Cópia de IMG_3763.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 0,
      "bilateralCandidates": 0,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "sem_candidato"
    },
    {
      "idx": 15,
      "paciente": "Paciente 13 - Pedro Gustavo Mendes Ponciano",
      "video": "Cópia de IMG_3940.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 17,
      "paciente": "Paciente 14 - Jocelia Santos de Oliveira",
      "video": "Cópia de IMG_3959.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 6,
      "bilateralCandidates": 1,
      "unilateralCandidates": 5,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 18,
      "paciente": "Paciente 15 - Aline de Sousa Lima Otoni",
      "video": "Cópia de IMG_3976.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 2,
      "bilateralCandidates": 1,
      "unilateralCandidates": 1,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 20,
      "paciente": "Paciente 16 - Rosemary Jerk ",
      "video": "Cópia de IMG_4220.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 2,
      "bilateralCandidates": 2,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 22,
      "paciente": "Paciente 17 - Thaissa Beatriz Costa Martins",
      "video": "Cópia de IMG_4246.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 0,
      "bilateralCandidates": 0,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "sem_candidato"
    },
    {
      "idx": 23,
      "paciente": "Paciente 17 - Thaissa Beatriz Costa Martins",
      "video": "Cópia de IMG_4247.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 12,
      "bilateralCandidates": 10,
      "unilateralCandidates": 2,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 29,
      "paciente": "Paciente 21 - Robson Ferreira de Sousa",
      "video": "IMG_4449.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 0,
      "unilateralCandidates": 1,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 34,
      "paciente": "Paciente 25 - Alejandro da Silva Santos",
      "video": "IMG_4540.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 11,
      "bilateralCandidates": 1,
      "unilateralCandidates": 10,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 35,
      "paciente": "Paciente 25 - Alejandro da Silva Santos",
      "video": "IMG_4541.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 15,
      "bilateralCandidates": 4,
      "unilateralCandidates": 11,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 39,
      "paciente": "Paciente 29 - Evandro Silva Siqueira",
      "video": "IMG_5030.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 40,
      "paciente": "Paciente 3 - José Ivo da Silva",
      "video": "Cópia de IMG_2680.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 47,
      "paciente": "Paciente 33 - Maria Nilza Barbosa ",
      "video": "IMG_6375.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 50,
      "paciente": "Paciente 35 - Ricardo Mendonça Feitosa",
      "video": "IMG_6423.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 7,
      "bilateralCandidates": 2,
      "unilateralCandidates": 5,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 51,
      "paciente": "Paciente 35 - Ricardo Mendonça Feitosa",
      "video": "IMG_6424.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 3,
      "bilateralCandidates": 0,
      "unilateralCandidates": 3,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 59,
      "paciente": "Paciente 42 - Márcia Verônica de Laurentis ",
      "video": "IMG_7575.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 12,
      "bilateralCandidates": 10,
      "unilateralCandidates": 2,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 60,
      "paciente": "Paciente 42 - Márcia Verônica de Laurentis ",
      "video": "IMG_7576.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 9,
      "bilateralCandidates": 2,
      "unilateralCandidates": 7,
      "requiresManualReview": true,
      "category": "alto_potencial"
    },
    {
      "idx": 66,
      "paciente": "Paciente 6 - Francisco Justiniano",
      "video": "Cópia de IMG_3103.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 0,
      "unilateralCandidates": 1,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    },
    {
      "idx": 70,
      "paciente": "Paciente 9 - Mariana Lambert",
      "video": "IMG_3653.MOV",
      "status": "success",
      "reprocessedBlinks": 0,
      "candidates": 1,
      "bilateralCandidates": 1,
      "unilateralCandidates": 0,
      "requiresManualReview": true,
      "category": "baixo_potencial"
    }
  ],
  "algorithmChanges": [
    "A abertura ocular usa EAR de 6 pontos, mais estável contra distância da câmera e escala do rosto.",
    "O detector usa baseline adaptativo por olho, em vez de depender apenas de um limiar fixo global.",
    "A métrica combinada agora sincroniza eventos esquerdo/direito e conta piscadas clínicas únicas.",
    "O total cru por olho permanece salvo para auditoria e comparação com versões anteriores.",
    "Piscadas longas demais ficam limitadas a 800 ms para reduzir falsos positivos por oclusão, movimento ou perda de rastreamento.",
    "Os vídeos com zero eventos ganharam uma varredura relaxada separada, sempre marcada como candidato para revisão manual."
  ],
  "clinicalNotes": [
    "A versão anterior somava eventos do olho esquerdo e direito; em piscadas bilaterais isso inflava o total.",
    "Os 87 eventos da recuperação não foram incorporados como piscadas confirmadas; eles são candidatos para auditoria manual.",
    "Paciente 23 segue como caso real de alto volume: 141 piscadas clínicas, todas bilaterais sincronizadas, com taxa de 44,6/min.",
    "Paciente 11 permanece com zero no detector principal; suas anotações sugerem piscadas incompletas muito sutis abaixo do limiar atual.",
    "Os vídeos zero e os casos de taxa alta devem formar o primeiro conjunto de anotação manual."
  ]
} as const;
